# Generated by Django 3.2.2 on 2021-10-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(blank=True, max_length=20, verbose_name='Tarea')),
                ('estado_tarea', models.BooleanField(verbose_name='Tarea completada')),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
    ]
